store:
    resource: "@StoreBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

product:
    resource: "@StoreBundle/Controller/"
    type:     annotation
